version: "3.9"  # optional since v1.27.0
services:
  backend:
    build: ./backend
    ports:
      - 8081:8080
    networks:
      - minio-net
  frontend:
    build: ./frontend
    ports:
      - 8082:8080
    environment:
      - VUE_APP_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - minio-net
networks:
  minio-net:
    driver: bridge