############################################################################
#                               Info
############################################################################
info:
  application:
    name: "Minisign Web - proof of concept"
    description: "Proof of concept"
    version: "0.0.1-SNAPSHOT"

############################################################################
#                               OpenApi
############################################################################

open-api-doc:
  application:
    name: ${info.application.name}
    description: ${info.application.description}
    version: ${info.application.version}
    port: ${server.port}

#############################################
# Logging
#############################################
logging:
  level:
    org.dddjourney: DEBUG

#############################################
# Spring Boot Framework
#############################################
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB