############################################################################
#                            Application
############################################################################
app:
  info:
    application:
      name: "Minisign Web - proof of concept"
      description: "Proof of concept"
      version: "0.0.1-SNAPSHOT"
  file-storage:
    upload-folder: file-upload
    download-folder: file-download

############################################################################
#                               OpenApi
############################################################################

open-api-doc:
  application:
    name: ${app-info.application.name}
    description: ${app.info.application.description}
    version: ${app.info.application.version}
    port: ${app.server.port}

############################################################################
# Logging
############################################################################
logging:
  level:
    org.dddjourney: DEBUG

############################################################################
# Spring Boot Framework
############################################################################
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB