############################################################################
#                            Application
############################################################################
app:
  file-storage:
    upload-folder: build/file-upload
    download-folder: build/file-download